/** Skript Builder — .sk file generator */

import { getEventSyntax } from './skriptData'

const TAB = '\t'

function indent(level) {
  return TAB.repeat(level)
}

function pushLines(lines, codeLines, level) {
  const prefix = indent(level)
  ;(codeLines || []).forEach(line => {
    const trimmed = String(line ?? '').trimEnd()
    if (!trimmed) {
      lines.push('')
      return
    }
    if (trimmed.startsWith('\t')) {
      lines.push(prefix + trimmed.slice(1))
      return
    }
    lines.push(prefix + trimmed)
  })
}

function pushBlock(lines, blockLines, level) {
  ;(blockLines || []).forEach(raw => {
    const line = String(raw ?? '')
    if (!line.trim()) {
      lines.push('')
      return
    }
    if (line.endsWith(':')) {
      lines.push(indent(level) + line.trim())
      return
    }
    lines.push(indent(level) + line.trim())
  })
}

function buildHeader(header) {
  const lines = []
  lines.push('# ═══════════════════════════════════════════════════════════')
  lines.push(`# Script: ${header.scriptName || 'unnamed'}`)
  if (header.author) lines.push(`# Author: ${header.author}`)
  if (header.version) lines.push(`# Version: ${header.version}`)
  if (header.description) lines.push(`# Description: ${header.description}`)
  if (header.includeTimestamp) {
    lines.push(`# Generated: ${new Date().toISOString().slice(0, 19).replace('T', ' ')} UTC`)
  }
  lines.push('# Generated by SConfig Skript Builder')
  lines.push('# Place in plugins/Skript/scripts/')
  lines.push('# ═══════════════════════════════════════════════════════════')
  lines.push('')
  return lines
}

function buildOptions(options) {
  const valid = (options || []).filter(o => o.key?.trim())
  if (!valid.length) return []
  const lines = ['options:']
  valid.forEach(o => {
    lines.push(`${TAB}${o.key.trim()}: ${o.value ?? ''}`)
  })
  lines.push('')
  return lines
}

function buildVariablesSection(variables) {
  const lines = []
  const load = (variables?.onLoad || []).filter(Boolean)
  const unload = (variables?.onUnload || []).filter(Boolean)

  if (load.length) {
    lines.push('on script load:')
    pushBlock(lines, load, 1)
    lines.push('')
  }
  if (unload.length) {
    lines.push('on script unload:')
    pushBlock(lines, unload, 1)
    lines.push('')
  }
  return lines
}

function buildCommand(cmd) {
  if (!cmd.enabled) return []
  const lines = []
  const path = (cmd.path || '/cmd').trim()
  const args = (cmd.args || '').trim()
  const fullPath = args ? `${path} ${args}` : path
  lines.push(`command ${fullPath}:`)

  if (cmd.prefix?.trim()) lines.push(`${TAB}prefix: ${cmd.prefix.trim()}`)
  if (cmd.description?.trim()) lines.push(`${TAB}description: ${cmd.description.trim()}`)
  if (cmd.usage?.trim()) lines.push(`${TAB}usage: ${cmd.usage.trim()}`)
  if (cmd.permission?.trim()) lines.push(`${TAB}permission: ${cmd.permission.trim()}`)
  if (cmd.permissionMessage?.trim()) lines.push(`${TAB}permission message: ${cmd.permissionMessage.trim()}`)

  const aliases = (cmd.aliases || []).filter(Boolean)
  if (aliases.length) lines.push(`${TAB}aliases: ${aliases.join(', ')}`)

  if (cmd.executableBy === 'console') lines.push(`${TAB}executable by: console`)
  else if (cmd.executableBy === 'both') lines.push(`${TAB}executable by: players and console`)

  if (cmd.cooldown > 0) {
    const unit = cmd.cooldownUnit || 'seconds'
    lines.push(`${TAB}cooldown: ${cmd.cooldown} ${unit}`)
    if (cmd.cooldownMessage?.trim()) lines.push(`${TAB}cooldown message: ${cmd.cooldownMessage.trim()}`)
    if (cmd.cooldownBypass?.trim()) lines.push(`${TAB}cooldown bypass: ${cmd.cooldownBypass.trim()}`)
    if (cmd.cooldownStorage === 'server') lines.push(`${TAB}cooldown storage: server`)
  }

  lines.push(`${TAB}trigger:`)

  const conditions = (cmd.conditions || []).filter(Boolean)
  const effects = (cmd.effects || []).filter(Boolean)
  const elseEffects = (cmd.elseEffects || []).filter(Boolean)

  if (conditions.length) {
    conditions.forEach((cond, i) => {
      const c = String(cond).trim()
      if (!c) return
      const prefix = i === 0 ? 'if ' : 'else if '
      const clause = c.startsWith('if ') ? c : `${prefix}${c}`
      lines.push(indent(2) + (i === 0 ? clause : clause.replace(/^if /, 'else if ')))
      if (!c.endsWith(':')) lines[lines.length - 1] += ':'
    })
    pushBlock(lines, effects, 3)
    if (elseEffects.length) {
      lines.push(indent(2) + 'else:')
      pushBlock(lines, elseEffects, 3)
    }
  } else {
    pushBlock(lines, effects, 2)
  }

  lines.push('')
  return lines
}

function buildEvent(evt) {
  if (!evt.enabled) return []
  const lines = []
  let eventLine = getEventSyntax(evt)

  if (evt.filter === 'uncancelled' || evt.filter === 'cancelled') {
    if (eventLine.startsWith('on ')) {
      eventLine = `on ${evt.filter} ${eventLine.slice(3)}`
    } else if (!eventLine.startsWith('every ') && !eventLine.startsWith('at ')) {
      eventLine = `on ${evt.filter} ${eventLine}`
    }
  }

  if (evt.priority && evt.priority !== 'normal') {
    eventLine += ` with priority ${evt.priority}`
  }

  lines.push(`${eventLine}:`)

  const conditions = (evt.conditions || []).filter(Boolean)
  const effects = (evt.effects || []).filter(Boolean)
  const elseEffects = (evt.elseEffects || []).filter(Boolean)

  if (conditions.length) {
    conditions.forEach((cond, i) => {
      const c = String(cond).trim()
      if (!c) return
      const line = i === 0 ? `if ${c.replace(/^if\s+/i, '')}` : `else if ${c.replace(/^(else\s+if|if)\s+/i, '')}`
      lines.push(indent(1) + line + (line.endsWith(':') ? '' : ':'))
    })
    pushBlock(lines, effects, 2)
    if (elseEffects.length) {
      lines.push(indent(1) + 'else:')
      pushBlock(lines, elseEffects, 2)
    }
  } else {
    pushBlock(lines, effects, 1)
  }

  lines.push('')
  return lines
}

function buildFunction(fn) {
  if (!fn.enabled) return []
  const lines = []
  const params = (fn.params || [])
    .filter(p => p.name?.trim())
    .map(p => `${p.name.trim()}: ${p.type || 'text'}`)
    .join(', ')

  const localPrefix = fn.local ? 'local ' : ''
  const ret = fn.returnType?.trim() ? ` :: ${fn.returnType.trim()}` : ''
  lines.push(`${localPrefix}function ${fn.name || 'unnamed'}(${params})${ret}:`)
  pushBlock(lines, fn.body || [], 1)
  lines.push('')
  return lines
}

function buildCustom(custom) {
  if (!custom?.enabled || !custom.code?.trim()) return []
  return [custom.code.trim(), '']
}

export function buildSkript(state) {
  const lines = []
  lines.push(...buildHeader(state.header))
  lines.push(...buildOptions(state.options))
  lines.push(...buildVariablesSection(state.variables))

  ;(state.commands || []).forEach(cmd => lines.push(...buildCommand(cmd)))
  ;(state.events || []).forEach(evt => lines.push(...buildEvent(evt)))
  ;(state.functions || []).forEach(fn => lines.push(...buildFunction(fn)))
  lines.push(...buildCustom(state.custom))

  return lines.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n'
}

export function downloadSkript(content, filename) {
  const name = filename?.endsWith('.sk') ? filename : `${filename || 'script'}.sk`
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = name
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

export function countLines(content) {
  return String(content || '').split('\n').length
}

export function countEnabled(state) {
  return {
    commands: (state.commands || []).filter(c => c.enabled).length,
    events: (state.events || []).filter(e => e.enabled).length,
    functions: (state.functions || []).filter(f => f.enabled).length,
  }
}
