/** ExcellentCrates Builder — YAML generator */

import { RARITIES } from './excellentCratesData.js'

function q(str) { return `'${String(str).replace(/'/g, "''")}'` }
function indent(n) { return '  '.repeat(n) }

function rarityWeight(rarityId) {
  const r = RARITIES.find(x => x.id === rarityId)
  return r ? r.weight : 50
}

// ── Generate crate config YAML ───────────────────────────────────────────────
export function buildCrateYaml(state) {
  const lines = []
  const { general, cost, cooldown, keys, rewards, animation, preview, effects, hologram, pushback, milestones, massOpen } = state

  lines.push(`# ═══════════════════════════════════════════════════════════`)
  lines.push(`# ExcellentCrates — Crate Configuration`)
  lines.push(`# Crate: ${general.id}`)
  lines.push(`# Generated by SConfig ExcellentCrates Builder`)
  lines.push(`# Place in: plugins/ExcellentCrates/crates/${general.id}.yml`)
  lines.push(`# ═══════════════════════════════════════════════════════════`)
  lines.push('')

  // Display name & description
  lines.push(`Name: ${q(general.displayName)}`)
  if (general.description.length > 0) {
    lines.push(`Description:`)
    general.description.forEach(d => lines.push(`  - ${q(d)}`))
  }
  lines.push('')

  // Permission
  if (general.permissionRequired && general.permission) {
    lines.push(`Permission:`)
    lines.push(`  Enabled: true`)
    lines.push(`  Node: ${q(general.permission)}`)
  } else {
    lines.push(`Permission:`)
    lines.push(`  Enabled: false`)
  }
  lines.push('')

  // Open cost
  lines.push(`Open_Cost:`)
  if (cost.type !== 'none' && cost.amount > 0) {
    lines.push(`  Enabled: true`)
    lines.push(`  Type: ${cost.type.toUpperCase()}`)
    lines.push(`  Amount: ${cost.amount}`)
  } else {
    lines.push(`  Enabled: false`)
  }
  lines.push('')

  // Open cooldown
  lines.push(`Open_Cooldown:`)
  if (cooldown.enabled && cooldown.amount > 0) {
    lines.push(`  Enabled: true`)
    lines.push(`  Amount: ${cooldown.amount}`)
    lines.push(`  Unit: ${cooldown.unit.toUpperCase()}`)
  } else {
    lines.push(`  Enabled: false`)
  }
  lines.push('')

  // Mass open
  lines.push(`Mass_Open:`)
  lines.push(`  Enabled: ${massOpen.enabled}`)
  if (massOpen.enabled) {
    lines.push(`  Max_Amount: ${massOpen.maxAmount}`)
  }
  lines.push('')

  // Pushback
  lines.push(`Pushback:`)
  lines.push(`  Enabled: ${pushback.enabled}`)
  if (pushback.enabled) {
    lines.push(`  Strength: ${pushback.strength}`)
  }
  lines.push('')

  // Keys
  lines.push(`Keys:`)
  keys.forEach((key, i) => {
    lines.push(`  '${key.id || `key_${i}`}':`)
    lines.push(`    Name: ${q(key.displayName)}`)
    lines.push(`    Type: ${key.type}`)
    lines.push(`    Item:`)
    lines.push(`      Material: ${key.material}`)
    lines.push(`      Name: ${q(key.displayName)}`)
    if (key.lore.length > 0) {
      lines.push(`      Lore:`)
      key.lore.forEach(l => lines.push(`        - ${q(l)}`))
    }
    if (key.glowing) {
      lines.push(`      Enchants:`)
      lines.push(`        UNBREAKING: 1`)
      lines.push(`      Flags:`)
      lines.push(`        - HIDE_ENCHANTS`)
    }
  })
  lines.push('')

  // Animation
  lines.push(`Animation:`)
  lines.push(`  Enabled: ${animation.enabled}`)
  if (animation.enabled) {
    lines.push(`  Type: ${animation.type.toUpperCase()}`)
    lines.push(`  Prevent_Skip: ${animation.preventSkip}`)
  }
  lines.push('')

  // Preview
  lines.push(`Preview:`)
  lines.push(`  Enabled: ${preview.enabled}`)
  if (preview.enabled) {
    lines.push(`  Title: ${q(preview.title)}`)
    lines.push(`  Size: ${preview.rows * 9}`)
  }
  lines.push('')

  // Block effects
  lines.push(`Block:`)
  lines.push(`  Effect:`)
  lines.push(`    Particle: ${effects.particle}`)
  if (effects.particleData) {
    lines.push(`    Data: ${q(effects.particleData)}`)
  }
  lines.push('')

  // Hologram
  lines.push(`  Hologram:`)
  lines.push(`    Enabled: ${hologram.enabled}`)
  if (hologram.enabled) {
    lines.push(`    Offset_Y: ${hologram.offsetY}`)
    lines.push(`    Lines:`)
    hologram.lines.forEach(l => lines.push(`      - ${q(l)}`))
  }
  lines.push('')

  // Rewards
  lines.push(`Rewards:`)
  rewards.forEach((rwd, i) => {
    if (!rwd.enabled) return
    const rwdId = rwd.name.replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase() || `reward_${i}`
    lines.push(`  '${rwdId}':`)
    lines.push(`    Name: ${q(rwd.displayName || rwd.name)}`)
    lines.push(`    Type: ${rwd.type.toUpperCase()}`)
    lines.push(`    Rarity: ${rwd.rarity}`)
    lines.push(`    Weight: ${rwd.weight}`)
    lines.push(`    Broadcast: ${rwd.broadcast}`)

    if (rwd.type === 'item') {
      lines.push(`    Item:`)
      lines.push(`      Material: ${rwd.material}`)
      lines.push(`      Amount: ${rwd.amount}`)
      if (rwd.displayName) lines.push(`      Name: ${q(rwd.displayName)}`)
      if (rwd.lore && rwd.lore.length > 0) {
        lines.push(`      Lore:`)
        rwd.lore.forEach(l => lines.push(`        - ${q(l)}`))
      }
      if (rwd.enchantments && rwd.enchantments.length > 0) {
        lines.push(`      Enchants:`)
        rwd.enchantments.forEach(e => lines.push(`        ${e.name}: ${e.level}`))
      }
    }

    if (rwd.type === 'command' && rwd.commands.length > 0) {
      lines.push(`    Commands:`)
      rwd.commands.forEach(c => lines.push(`      - ${q(c)}`))
      // Command rewards need a preview icon
      lines.push(`    Preview:`)
      lines.push(`      Material: ${rwd.material || 'PAPER'}`)
      lines.push(`      Name: ${q(rwd.displayName || rwd.name)}`)
      if (rwd.lore && rwd.lore.length > 0) {
        lines.push(`      Lore:`)
        rwd.lore.forEach(l => lines.push(`        - ${q(l)}`))
      }
    }

    // Win limits
    if (rwd.winLimitEnabled) {
      lines.push(`    Win_Limit:`)
      lines.push(`      Enabled: true`)
      lines.push(`      Amount: ${rwd.winLimitAmount}`)
      if (rwd.winLimitCooldown > 0) {
        lines.push(`      Cooldown: ${rwd.winLimitCooldown}`)
        lines.push(`      Cooldown_Unit: ${(rwd.winLimitCooldownUnit || 'hours').toUpperCase()}`)
      }
    }

    if (rwd.globalLimitEnabled) {
      lines.push(`    Global_Win_Limit:`)
      lines.push(`      Enabled: true`)
      lines.push(`      Amount: ${rwd.globalLimitAmount}`)
      if (rwd.globalLimitCooldown > 0) {
        lines.push(`      Cooldown: ${rwd.globalLimitCooldown}`)
        lines.push(`      Cooldown_Unit: ${(rwd.globalLimitCooldownUnit || 'hours').toUpperCase()}`)
      }
    }
    lines.push('')
  })

  // Milestones
  if (milestones.length > 0) {
    lines.push(`Milestones:`)
    milestones.forEach((ms, i) => {
      lines.push(`  '${ms.openings}':`)
      lines.push(`    Openings: ${ms.openings}`)
      lines.push(`    Rewards:`)
      ms.rewards.forEach((rwd, j) => {
        lines.push(`      'milestone_${ms.openings}_${j}':`)
        lines.push(`        Name: ${q(rwd.displayName || rwd.name)}`)
        lines.push(`        Type: COMMAND`)
        if (rwd.commands && rwd.commands.length > 0) {
          lines.push(`        Commands:`)
          rwd.commands.forEach(c => lines.push(`          - ${q(c)}`))
        }
      })
    })
    lines.push('')
  }

  return lines.join('\n')
}

// ── Generate key config YAML ─────────────────────────────────────────────────
export function buildKeyYaml(key) {
  const lines = []
  lines.push(`# ExcellentCrates Key Configuration`)
  lines.push(`# Place in: plugins/ExcellentCrates/keys/${key.id}.yml`)
  lines.push('')
  lines.push(`Name: ${q(key.displayName)}`)
  lines.push(`Type: ${key.type}`)
  lines.push(`Item:`)
  lines.push(`  Material: ${key.material}`)
  lines.push(`  Name: ${q(key.displayName)}`)
  if (key.lore && key.lore.length > 0) {
    lines.push(`  Lore:`)
    key.lore.forEach(l => lines.push(`    - ${q(l)}`))
  }
  if (key.glowing) {
    lines.push(`  Enchants:`)
    lines.push(`    UNBREAKING: 1`)
    lines.push(`  Flags:`)
    lines.push(`    - HIDE_ENCHANTS`)
  }
  return lines.join('\n')
}

// ── Download helper ──────────────────────────────────────────────────────────
export function downloadYaml(content, filename) {
  const name = filename?.endsWith('.yml') ? filename : `${filename || 'crate'}.yml`
  const blob = new Blob([content], { type: 'text/yaml;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = name
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

export function countRewards(state) {
  return {
    total: state.rewards.length,
    enabled: state.rewards.filter(r => r.enabled).length,
    items: state.rewards.filter(r => r.type === 'item' && r.enabled).length,
    commands: state.rewards.filter(r => r.type === 'command' && r.enabled).length,
  }
}
