import { CHECK_CATALOG } from './vulcanData'

function indent(level) {
  return '  '.repeat(level)
}

function quoteStr(s) {
  const str = String(s ?? '')
  if (str.includes("'") && !str.includes('"')) return `"${str}"`
  if (str.includes('"')) return `'${str.replace(/'/g, "''")}'`
  return `'${str}'`
}

function formatScalar(v) {
  if (v === true) return 'true'
  if (v === false) return 'false'
  if (typeof v === 'number') return String(v)
  const s = String(v ?? '').trim()
  if (s === '') return "''"
  if (/^-?\d+(\.\d+)?$/.test(s)) return s
  return quoteStr(s)
}

function writeStringList(lines, items, level) {
  ;(items || []).forEach(item => {
    const t = String(item).trim()
    if (t) lines.push(`${indent(level)}- ${formatScalar(t)}`)
  })
}

function writeCheckBlock(lines, chk, level) {
  lines.push(`${indent(level)}enabled: ${formatScalar(chk.enabled)}`)
  lines.push(`${indent(level)}punishable: ${formatScalar(chk.punishable)}`)
  lines.push(`${indent(level)}broadcast-punishment: ${formatScalar(chk.broadcastPunishment)}`)
  lines.push(`${indent(level)}max-violations: ${formatScalar(chk.maxViolations)}`)
  lines.push(`${indent(level)}alert-interval: ${formatScalar(chk.alertInterval)}`)
  lines.push(`${indent(level)}dont-alert-until: ${formatScalar(chk.dontAlertUntil)}`)
  lines.push(`${indent(level)}maximum-ping: ${formatScalar(chk.maximumPing)}`)
  lines.push(`${indent(level)}minimum-tps: ${formatScalar(chk.minimumTps)}`)
  lines.push(`${indent(level)}punishment-commands:`)
  writeStringList(lines, chk.punishmentCommands, level + 1)
  lines.push(`${indent(level)}buffer:`)
  lines.push(`${indent(level + 1)}max: ${formatScalar(chk.bufferMax)}`)
  lines.push(`${indent(level + 1)}multiple: ${formatScalar(chk.bufferMultiple)}`)
  lines.push(`${indent(level + 1)}decay: ${formatScalar(chk.bufferDecay)}`)
}

function buildChecksSection(s) {
  const tree = {}
  CHECK_CATALOG.forEach(meta => {
    const chk = s.checks?.[meta.id]
    if (!chk) return
    if (!tree[meta.category]) tree[meta.category] = {}
    if (!tree[meta.category][meta.group]) tree[meta.category][meta.group] = {}
    tree[meta.category][meta.group][meta.type] = chk
  })

  const out = ['checks:']
  Object.entries(tree).forEach(([cat, groups]) => {
    out.push(`${indent(1)}${cat}:`)
    Object.entries(groups).forEach(([group, types]) => {
      out.push(`${indent(2)}${group}:`)
      Object.entries(types).forEach(([type, chk]) => {
        out.push(`${indent(3)}${type}:`)
        writeCheckBlock(out, chk, 4)
        out.push('')
      })
    })
  })
  return out.join('\n').trimEnd()
}

export function buildConfigYaml(s) {
  const parts = [
    '# Vulcan Anti-Cheat — generated by SConfig',
    '# https://vulcanac.net/',
    '',
    `prefix: ${formatScalar(s.prefix)}`,
    '',
    'alerts:',
    `${indent(1)}format: ${formatScalar(s.alerts?.format)}`,
    `${indent(1)}print-to-console: ${formatScalar(s.alerts?.printToConsole)}`,
    `${indent(1)}console-format: ${formatScalar(s.alerts?.consoleFormat)}`,
    `${indent(1)}experimental-symbol: ${formatScalar(s.alerts?.experimentalSymbol)}`,
    `${indent(1)}toggled-on-message: ${formatScalar(s.alerts?.toggledOnMessage)}`,
    `${indent(1)}toggled-off-message: ${formatScalar(s.alerts?.toggledOffMessage)}`,
    `${indent(1)}click-commands:`,
  ]
  writeStringList(parts, s.alerts?.clickCommands, 1)
  parts.push(`${indent(1)}click-alert-command-commands:`)
  writeStringList(parts, s.alerts?.clickAlertCommands, 1)
  parts.push(
    '',
    'log-file:',
    `${indent(1)}enabled: ${formatScalar(s.logFile?.enabled)}`,
    `${indent(1)}alert-message: ${formatScalar(s.logFile?.alertMessage)}`,
    `${indent(1)}punishment-message: ${formatScalar(s.logFile?.punishmentMessage)}`,
    '',
    'violation-reset:',
    `${indent(1)}enabled: ${formatScalar(s.violationReset?.enabled)}`,
    `${indent(1)}interval-in-minutes: ${formatScalar(s.violationReset?.intervalMinutes)}`,
    `${indent(1)}message-enabled: ${formatScalar(s.violationReset?.messageEnabled)}`,
    `${indent(1)}message: ${formatScalar(s.violationReset?.message)}`,
    '',
    'client-brand-alerts:',
    `${indent(1)}resolve: ${formatScalar(s.clientBrand?.resolve)}`,
    `${indent(1)}enabled: ${formatScalar(s.clientBrand?.enabled)}`,
    `${indent(1)}ignore-alerts-list:`,
  )
  writeStringList(parts, s.clientBrand?.ignoreAlertsList, 1)
  parts.push(
    `${indent(1)}message: ${formatScalar(s.clientBrand?.message)}`,
    `${indent(1)}blocked-client-brands:`,
  )
  writeStringList(parts, s.clientBrand?.blockedBrands, 1)
  parts.push(
    `${indent(1)}unallowed-client-brand-kick-message: ${formatScalar(s.clientBrand?.unallowedKickMessage)}`,
    `${indent(1)}whitelist-enabled: ${formatScalar(s.clientBrand?.whitelistEnabled)}`,
    `${indent(1)}whitelisted-client-brands:`,
  )
  writeStringList(parts, s.clientBrand?.whitelistedBrands, 1)
  parts.push(
    '',
    'connection:',
    `${indent(1)}debug-messages: ${formatScalar(s.connection?.debugMessages)}`,
    `${indent(1)}other-anticheat-support: ${formatScalar(s.connection?.otherAnticheatSupport)}`,
    `${indent(1)}no-response:`,
    `${indent(2)}delay-in-seconds: ${formatScalar(s.connection?.noResponseDelay)}`,
    `${indent(1)}max-size:`,
    `${indent(2)}amount: ${formatScalar(s.connection?.maxSizeAmount)}`,
    `${indent(1)}keepalive:`,
    `${indent(2)}kick-enabled: ${formatScalar(s.connection?.keepaliveKick)}`,
    `${indent(2)}max-delay: ${formatScalar(s.connection?.keepaliveMaxDelay)}`,
    `${indent(1)}max-ping:`,
    `${indent(2)}kick-enabled: ${formatScalar(s.connection?.maxPingKick)}`,
    `${indent(2)}max-ping: ${formatScalar(s.connection?.maxPingValue)}`,
    `${indent(2)}max-ticks: ${formatScalar(s.connection?.maxPingTicks)}`,
    '',
    'punishments:',
    `${indent(1)}message: ${formatScalar(s.punishments?.message)}`,
    '',
    'ghost-blocks-fix:',
    `${indent(1)}enabled: ${formatScalar(s.ghostBlocks?.enabled)}`,
    `${indent(1)}ghost-water-fix: ${formatScalar(s.ghostBlocks?.ghostWaterFix)}`,
    `${indent(1)}minimum-tps: ${formatScalar(s.ghostBlocks?.minimumTps)}`,
    `${indent(1)}setback: ${formatScalar(s.ghostBlocks?.setback)}`,
    `${indent(1)}ticks: ${formatScalar(s.ghostBlocks?.ticks)}`,
    `${indent(1)}staff-message-enabled: ${formatScalar(s.ghostBlocks?.staffMessageEnabled)}`,
    '',
    'settings:',
    `${indent(1)}toggle-alerts-on-join: ${formatScalar(s.settings?.toggleAlertsOnJoin)}`,
    `${indent(1)}per-check-severities: ${formatScalar(s.settings?.perCheckSeverities)}`,
    `${indent(1)}check-for-updates: ${formatScalar(s.settings?.checkForUpdates)}`,
    `${indent(1)}async-alerts: ${formatScalar(s.settings?.asyncAlerts)}`,
    `${indent(1)}max-alert-violation: ${formatScalar(s.settings?.maxAlertViolation)}`,
    `${indent(1)}punishment-delay: ${formatScalar(s.settings?.punishmentDelay)}`,
    `${indent(1)}ignore-floodgate: ${formatScalar(s.settings?.ignoreFloodgate)}`,
    `${indent(1)}join-check-wait-time: ${formatScalar(s.settings?.joinCheckWaitTime)}`,
    `${indent(1)}max-logs-file-size: ${formatScalar(s.settings?.maxLogsFileSize)}`,
    `${indent(1)}server-name: ${formatScalar(s.settings?.serverName)}`,
    `${indent(1)}flight-cooldown: ${formatScalar(s.settings?.flightCooldown)}`,
    `${indent(1)}lenient-scaffolding: ${formatScalar(s.settings?.lenientScaffolding)}`,
    `${indent(1)}entity-collision: ${formatScalar(s.settings?.entityCollision)}`,
    `${indent(1)}plugin-messaging: ${formatScalar(s.settings?.pluginMessaging)}`,
    `${indent(1)}debug: ${formatScalar(s.settings?.debug)}`,
    '',
    'discord-webhook:',
    `${indent(1)}alerts:`,
    `${indent(2)}enabled: ${formatScalar(s.discord?.alertsEnabled)}`,
    `${indent(2)}url: ${formatScalar(s.discord?.alertsUrl)}`,
    `${indent(2)}username: ${formatScalar(s.discord?.username)}`,
    `${indent(2)}title: ${formatScalar(s.discord?.alertTitle)}`,
    `${indent(1)}punishments:`,
    `${indent(2)}enabled: ${formatScalar(s.discord?.punishmentsEnabled)}`,
    `${indent(2)}url: ${formatScalar(s.discord?.punishmentsUrl)}`,
    `${indent(2)}title: ${formatScalar(s.discord?.punishmentTitle)}`,
    '',
    buildChecksSection(s),
    '',
  )

  return parts.join('\n')
}

export function downloadYaml(content, filename) {
  const blob = new Blob([content], { type: 'text/yaml' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}
