function indent(level) {
  return '  '.repeat(level)
}

function quoteStr(s) {
  const str = String(s ?? '')
  if (str.includes("'") && !str.includes('"')) return `"${str}"`
  if (str.includes('"')) return `'${str.replace(/'/g, "''")}'`
  return `'${str}'`
}

function formatScalar(v) {
  if (v === true) return 'true'
  if (v === false) return 'false'
  if (typeof v === 'number') return String(v)
  const s = String(v ?? '').trim()
  if (s === '') return "''"
  if (/^-?\d+(\.\d+)?$/.test(s)) return s
  return quoteStr(s)
}

function writeStringList(lines, items, level) {
  ;(items || []).forEach(item => {
    const t = String(item).trim()
    if (t) lines.push(`${indent(level)}- ${formatScalar(t)}`)
  })
}

export function buildConfigYaml(s) {
  const lines = [
    '# SmartSpawner — generated by SConfig',
    '# https://docs.smartspawner.site/',
    '',
    `language: ${formatScalar(s.language)}`,
    `gui_layout: ${formatScalar(s.guiLayout)}`,
    `debug: ${formatScalar(s.debug)}`,
    '',
    'spawner_properties:',
    '  default:',
    `${indent(2)}min_mobs: ${formatScalar(s.spawnerProperties.minMobs)}`,
    `${indent(2)}max_mobs: ${formatScalar(s.spawnerProperties.maxMobs)}`,
    `${indent(2)}range: ${formatScalar(s.spawnerProperties.range)}`,
    `${indent(2)}delay: ${formatScalar(s.spawnerProperties.delay)}`,
    `${indent(2)}max_storage_pages: ${formatScalar(s.spawnerProperties.maxStoragePages)}`,
    `${indent(2)}max_stored_exp: ${formatScalar(s.spawnerProperties.maxStoredExp)}`,
    `${indent(2)}max_stack_size: ${formatScalar(s.spawnerProperties.maxStackSize)}`,
    `${indent(2)}allow_exp_mending: ${formatScalar(s.spawnerProperties.allowExpMending)}`,
    `${indent(2)}protect_from_explosions: ${formatScalar(s.spawnerProperties.protectFromExplosions)}`,
    '',
    'spawner_break:',
    `${indent(1)}enabled: ${formatScalar(s.spawnerBreak.enabled)}`,
    `${indent(1)}direct_to_inventory: ${formatScalar(s.spawnerBreak.directToInventory)}`,
    `${indent(1)}required_tools:`,
  ]
  writeStringList(lines, s.spawnerBreak.requiredTools, 1)
  lines.push(
    `${indent(1)}durability_loss: ${formatScalar(s.spawnerBreak.durabilityLoss)}`,
    `${indent(1)}auto_sell_and_claim_exp_on_break: ${formatScalar(s.spawnerBreak.autoSellAndClaimExpOnBreak)}`,
    `${indent(1)}silk_touch:`,
    `${indent(2)}required: ${formatScalar(s.spawnerBreak.silkTouch.required)}`,
    `${indent(2)}level: ${formatScalar(s.spawnerBreak.silkTouch.level)}`,
    '',
    'natural_spawner:',
    `${indent(1)}breakable: ${formatScalar(s.naturalSpawner.breakable)}`,
    `${indent(1)}convert_to_smart_spawner: ${formatScalar(s.naturalSpawner.convertToSmartSpawner)}`,
    `${indent(1)}spawn_mobs: ${formatScalar(s.naturalSpawner.spawnMobs)}`,
    `${indent(1)}protect_from_explosions: ${formatScalar(s.naturalSpawner.protectFromExplosions)}`,
    '',
    'sell_integration:',
    `${indent(1)}enabled: ${formatScalar(s.sellIntegration.enabled)}`,
    `${indent(1)}currency: ${formatScalar(s.sellIntegration.currency)}`,
    `${indent(1)}excellenteconomy_currency: ${formatScalar(s.sellIntegration.excellenteconomyCurrency)}`,
    `${indent(1)}price_source_mode: ${formatScalar(s.sellIntegration.priceSourceMode)}`,
    `${indent(1)}shop_integration:`,
    `${indent(2)}enabled: ${formatScalar(s.sellIntegration.shopIntegration.enabled)}`,
    `${indent(2)}preferred_plugin: ${formatScalar(s.sellIntegration.shopIntegration.preferredPlugin)}`,
    `${indent(1)}custom_prices:`,
    `${indent(2)}enabled: ${formatScalar(s.sellIntegration.customPrices.enabled)}`,
    `${indent(2)}default_price: ${formatScalar(s.sellIntegration.customPrices.defaultPrice)}`,
    '',
    'hopper:',
    `${indent(1)}enabled: ${formatScalar(s.hopper.enabled)}`,
    `${indent(1)}check_delay: ${formatScalar(s.hopper.checkDelay)}`,
    `${indent(1)}stack_per_transfer: ${formatScalar(s.hopper.stackPerTransfer)}`,
    '',
    'bedrock_support:',
    `${indent(1)}enable_formui: ${formatScalar(s.bedrockSupport.enableFormui)}`,
    '',
    'hologram:',
    `${indent(1)}enabled: ${formatScalar(s.hologram.enabled)}`,
    `${indent(1)}offset_x: ${formatScalar(s.hologram.offsetX)}`,
    `${indent(1)}offset_y: ${formatScalar(s.hologram.offsetY)}`,
    `${indent(1)}offset_z: ${formatScalar(s.hologram.offsetZ)}`,
    `${indent(1)}alignment: ${formatScalar(s.hologram.alignment)}`,
    `${indent(1)}shadowed_text: ${formatScalar(s.hologram.shadowedText)}`,
    `${indent(1)}see_through: ${formatScalar(s.hologram.seeThrough)}`,
    `${indent(1)}transparent_background: ${formatScalar(s.hologram.transparentBackground)}`,
    '',
    'particle:',
    `${indent(1)}spawner_stack: ${formatScalar(s.particle.spawnerStack)}`,
    `${indent(1)}spawner_activate: ${formatScalar(s.particle.spawnerActivate)}`,
    `${indent(1)}spawner_generate_loot: ${formatScalar(s.particle.spawnerGenerateLoot)}`,
    '',
    'logging:',
    `${indent(1)}enabled: ${formatScalar(s.logging.enabled)}`,
    `${indent(1)}json_format: ${formatScalar(s.logging.jsonFormat)}`,
    `${indent(1)}console_output: ${formatScalar(s.logging.consoleOutput)}`,
    `${indent(1)}max_log_files: ${formatScalar(s.logging.maxLogFiles)}`,
    `${indent(1)}max_log_size_mb: ${formatScalar(s.logging.maxLogSizeMb)}`,
    `${indent(1)}log_all_events: ${formatScalar(s.logging.logAllEvents)}`,
    `${indent(1)}logged_events:`,
  )
  writeStringList(lines, s.logging.loggedEvents, 1)
  lines.push(
    '',
    'database:',
    `${indent(1)}mode: ${formatScalar(s.database.mode)}`,
    `${indent(1)}server_name: ${formatScalar(s.database.serverName)}`,
    `${indent(1)}sync_across_servers: ${formatScalar(s.database.syncAcrossServers)}`,
    `${indent(1)}migrate_from_local: ${formatScalar(s.database.migrateFromLocal)}`,
    `${indent(1)}database: ${formatScalar(s.database.database)}`,
    `${indent(1)}sqlite:`,
    `${indent(2)}file: ${formatScalar(s.database.sqlite.file)}`,
    `${indent(1)}sql:`,
    `${indent(2)}host: ${formatScalar(s.database.sql.host)}`,
    `${indent(2)}port: ${formatScalar(s.database.sql.port)}`,
    `${indent(2)}username: ${formatScalar(s.database.sql.username)}`,
    `${indent(2)}password: ${formatScalar(s.database.sql.password)}`,
    `${indent(2)}pool:`,
    `${indent(3)}maximum-size: ${formatScalar(s.database.sql.pool.maximumSize)}`,
    `${indent(3)}minimum-idle: ${formatScalar(s.database.sql.pool.minimumIdle)}`,
    `${indent(3)}connection-timeout: ${formatScalar(s.database.sql.pool.connectionTimeout)}`,
    `${indent(3)}max-lifetime: ${formatScalar(s.database.sql.pool.maxLifetime)}`,
    `${indent(3)}idle-timeout: ${formatScalar(s.database.sql.pool.idleTimeout)}`,
    `${indent(3)}keepalive-time: ${formatScalar(s.database.sql.pool.keepaliveTime)}`,
    `${indent(3)}leak-detection-threshold: ${formatScalar(s.database.sql.pool.leakDetectionThreshold)}`,
    '',
    'performance:',
    '  loot_generation:',
    `${indent(2)}approximate_loot: ${formatScalar(s.performance.approximateLoot)}`,
    `${indent(2)}approximation_threshold: ${formatScalar(s.performance.approximationThreshold)}`,
  )
  return lines.join('\n')
}

export function buildItemPricesYaml(s) {
  const lines = [
    '# SmartSpawner item_prices.yml — generated by SConfig',
    '# Custom sell prices when sell_integration.custom_prices is enabled',
    '',
  ]
  Object.entries(s.itemPrices || {})
    .sort(([a], [b]) => a.localeCompare(b))
    .forEach(([item, price]) => {
      lines.push(`${item}: ${price}`)
    })
  return lines.join('\n')
}

export function buildSpawnersSettingsYaml(s) {
  const ss = s.spawnersSettings || {}
  const lines = [
    '# SmartSpawner spawners_settings.yml — generated by SConfig',
    '# https://docs.smartspawner.site/',
    '',
    `default_material: ${formatScalar(ss.defaultMaterial || 'SPAWNER')}`,
    '',
  ]

  Object.keys(ss.mobs || {}).sort().forEach(mobId => {
    const mob = ss.mobs[mobId]
    lines.push(`${mobId}:`)
    lines.push(`${indent(1)}experience: ${formatScalar(mob.experience)}`)
    const lootKeys = Object.keys(mob.loot || {})
    if (lootKeys.length > 0) {
      lines.push(`${indent(1)}loot:`)
      lootKeys.forEach(itemId => {
        const drop = mob.loot[itemId]
        lines.push(`${indent(2)}${itemId}:`)
        lines.push(`${indent(3)}amount: ${formatScalar(drop.amount)}`)
        lines.push(`${indent(3)}chance: ${formatScalar(drop.chance)}`)
        if (drop.durability != null && drop.durability !== '') {
          lines.push(`${indent(3)}durability: ${formatScalar(drop.durability)}`)
        }
        if (drop.potionType) {
          lines.push(`${indent(3)}potion_type: ${formatScalar(drop.potionType)}`)
        }
        if (drop.extended != null) {
          lines.push(`${indent(3)}extended: ${formatScalar(drop.extended)}`)
        }
        if (drop.upgraded != null) {
          lines.push(`${indent(3)}upgraded: ${formatScalar(drop.upgraded)}`)
        }
      })
    }
    const ht = mob.headTexture || {}
    lines.push(`${indent(1)}head_texture:`)
    lines.push(`${indent(2)}material: ${formatScalar(ht.material || 'PLAYER_HEAD')}`)
    if (ht.customTexture) {
      lines.push(`${indent(2)}custom_texture: ${formatScalar(ht.customTexture)}`)
    }
    lines.push('')
  })

  return lines.join('\n').trimEnd()
}

export function downloadText(content, filename) {
  const blob = new Blob([content], { type: 'text/yaml' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}
