function yamlQuote(str) {
  if (str == null) return '""'
  return `"${String(str).replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`
}

function yamlBool(v) {
  return v ? 'true' : 'false'
}

function yamlList(key, items, indent = 0) {
  const pad = ' '.repeat(indent)
  if (!items?.length) return [`${pad}${key}: []`]
  const out = [`${pad}${key}:`]
  items.forEach(item => {
    if (typeof item === 'string') out.push(`${pad}  - ${yamlQuote(item)}`)
    else out.push(`${pad}  - ${item}`)
  })
  return out
}

function buildItemYaml(key, item) {
  const lines = [`  '${key}':`]
  lines.push(`    material: ${item.material || 'STONE'}`)
  if (item.amount && item.amount !== 1) lines.push(`    amount: ${item.amount}`)
  lines.push(`    slot: ${item.slot}`)
  if (item.displayName) lines.push(`    display_name: ${yamlQuote(item.displayName)}`)
  if (item.lore?.length) lines.push(...yamlList('lore', item.lore, 4))
  if (item.priority) lines.push(`    priority: ${item.priority}`)
  if (item.update) lines.push(`    update: true`)
  if (item.hideAttributes) lines.push(`    hide_attributes: true`)
  if (item.hideEnchantments) lines.push(`    hide_enchantments: true`)
  if (item.glow) lines.push(`    glow: true`)
  if (item.viewRequirement?.trim()) lines.push(`    view_requirement: ${yamlQuote(item.viewRequirement)}`)
  if (item.leftClick?.length) lines.push(...yamlList('left_click_commands', item.leftClick, 4))
  if (item.rightClick?.length) lines.push(...yamlList('right_click_commands', item.rightClick, 4))
  if (item.middleClick?.length) lines.push(...yamlList('middle_click_commands', item.middleClick, 4))
  if (item.shiftLeftClick?.length) lines.push(...yamlList('shift_left_click_commands', item.shiftLeftClick, 4))
  if (item.shiftRightClick?.length) lines.push(...yamlList('shift_right_click_commands', item.shiftRightClick, 4))
  return lines
}

export function buildDeluxeMenuYaml(state) {
  const lines = [
    '# DeluxeMenus — generated by SConfig',
    '',
    `menu_title: ${yamlQuote(state.menuTitle)}`,
    `open_command: ${state.openCommand || 'menu'}`,
    `register_command: ${yamlBool(state.registerCommand)}`,
  ]

  if (state.openCommandAliases?.length) {
    lines.push(...yamlList('open_command_aliases', state.openCommandAliases, 0))
  }

  if (state.inventoryType && state.inventoryType !== 'CHEST') {
    lines.push(`inventory_type: ${state.inventoryType}`)
  }

  if (['CHEST', 'ENDER_CHEST', 'SHULKER_BOX'].includes(state.inventoryType)) {
    lines.push(`size: ${state.size}`)
  }

  if (state.updateInterval && state.updateInterval !== 20) {
    lines.push(`update_interval: ${state.updateInterval}`)
  }

  if (state.openRequirements?.trim()) {
    lines.push(`open_requirement:`)
    lines.push(`  requirements:`)
    lines.push(`    default:`)
    lines.push(`      type: has permission`)
    lines.push(`      permission: ${state.openRequirements.trim()}`)
  }

  if (state.openCommands?.length) lines.push(...yamlList('open_commands', state.openCommands, 0))
  if (state.closeCommands?.length) lines.push(...yamlList('close_commands', state.closeCommands, 0))

  const itemEntries = Object.values(state.items || {}).sort((a, b) => a.slot - b.slot)
  if (itemEntries.length) {
    lines.push('', 'items:')
    itemEntries.forEach((item, i) => {
      lines.push(...buildItemYaml(String(item.slot ?? i), item))
    })
  }

  return lines.join('\n').trim() + '\n'
}

export function downloadText(content, filename) {
  const blob = new Blob([content], { type: 'text/yaml;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}
