import { yamlQuote } from '../shopShared'
import { buildTradeItemYaml } from './shopKeeperData'

function buildTradeYaml(trade, idx) {
  const lines = [`    '${idx}':`]
  lines.push(...buildTradeItemYaml(trade.cost1, 6, 'item1'))
  if (trade.cost2?.material) lines.push(...buildTradeItemYaml(trade.cost2, 6, 'item2'))
  lines.push(...buildTradeItemYaml(trade.result, 6, 'resultItem'))
  if (trade.maxUses >= 0) lines.push(`      maxUses: ${trade.maxUses}`)
  return lines
}

export function buildShopkeeperSaveSnippet(sk) {
  const lines = [
    '# Shopkeepers — generated by SConfig',
    '# Admin shop trade template (merge into save.yml or use in-game editor)',
    '# Shop type: ' + sk.shopType,
    '',
    'shop:',
    `  name: ${yamlQuote(sk.name)}`,
    `  type: ${sk.shopType === 'admin' ? 'admin-shop' : sk.shopType + '-shop'}`,
    `  object-type: ${(sk.objectType || 'VILLAGER').toLowerCase()}`,
    '  trades:',
  ]
  sk.trades.forEach((tr, i) => lines.push(...buildTradeYaml(tr, i)))
  return lines.join('\n').trim() + '\n'
}

export function buildShopkeeperConfigSnippet(sk) {
  const lines = [
    '# Shopkeepers config snippet — currency & creation item',
    `currency-item: ${sk.currencyItem || 'EMERALD'}`,
    'shop-creation-item:',
    "  id: 'minecraft:villager_spawn_egg'",
    '  components:',
    "    minecraft:custom_name: '{color:\"green\",italic:0b,text:\"Shopkeeper\"}'",
    '',
    `# Location hint: ${sk.location?.world} ${sk.location?.x}, ${sk.location?.y}, ${sk.location?.z}`,
  ]
  return lines.join('\n').trim() + '\n'
}

export function buildFullExport(sk) {
  return `${buildShopkeeperSaveSnippet(sk)}\n${buildShopkeeperConfigSnippet(sk)}`
}

export function buildShopkeeperCommands(sk) {
  return [
    `# Shopkeepers commands for: ${sk.name.replace(/&[0-9a-fk-or]/gi, '')}`,
    '/shopkeeper create ' + (sk.shopType === 'admin' ? 'admin' : sk.shopType),
    sk.objectType !== 'VILLAGER' ? `/shopkeeper setobject ${sk.objectType.toLowerCase()}` : '',
    '/shopkeeper name ' + sk.name,
    '# Add trades via in-game editor after placing',
  ].filter(Boolean).join('\n')
}
