function indent(level) {
  return '  '.repeat(level)
}

function quoteStr(s) {
  const str = String(s ?? '')
  if (str.includes("'") && !str.includes('"')) return `"${str}"`
  if (str.includes('"')) return `'${str.replace(/'/g, "''")}'`
  return `'${str}'`
}

function formatScalar(v) {
  if (v === true) return 'true'
  if (v === false) return 'false'
  if (typeof v === 'number') return String(v)
  const s = String(v ?? '').trim()
  if (s === '') return "''"
  if (/^-?\d+(\.\d+)?$/.test(s)) return s
  return quoteStr(s)
}

function writeStringList(lines, list, level) {
  ;(list || []).forEach(item => {
    const t = String(item ?? '').trim()
    if (t) lines.push(`${indent(level)}- ${formatScalar(t)}`)
  })
}

function writeMap(lines, map, level) {
  Object.entries(map || {}).forEach(([key, value]) => {
    if (Array.isArray(value)) {
      lines.push(`${indent(level)}${key}:`)
      writeStringList(lines, value, level + 1)
      return
    }
    if (value && typeof value === 'object') {
      lines.push(`${indent(level)}${key}:`)
      writeMap(lines, value, level + 1)
      return
    }
    lines.push(`${indent(level)}${key}: ${formatScalar(value)}`)
  })
}

export function buildSettingsYaml(s) {
  const lines = [
    '# TotemGuard settings — generated by SConfig',
    '',
    `api: ${formatScalar(s.api)}`,
    `server: ${formatScalar(s.server)}`,
    `command: ${formatScalar(s.command)}`,
    'command-aliases:',
  ]
  writeStringList(lines, s.commandAliases, 1)
  lines.push(
    `bypass: ${formatScalar(s.bypass)}`,
    `console-alerts: ${formatScalar(s.consoleAlerts)}`,
    `announce-client-brand: ${formatScalar(s.announceClientBrand)}`,
    `announce-check-command: ${formatScalar(s.announceCheckCommand)}`,
    '',
    'redis:',
    `${indent(1)}enabled: ${formatScalar(s.redis?.enabled)}`,
    `${indent(1)}sync-alerts: ${formatScalar(s.redis?.syncAlerts)}`,
    `${indent(1)}channel: ${formatScalar(s.redis?.channel)}`,
    `${indent(1)}host: ${formatScalar(s.redis?.host)}`,
    `${indent(1)}port: ${formatScalar(s.redis?.port)}`,
    `${indent(1)}username: ${formatScalar(s.redis?.username)}`,
    `${indent(1)}password: ${formatScalar(s.redis?.password)}`,
    '',
    'database:',
    `${indent(1)}type: ${formatScalar(s.database?.type)}`,
    `${indent(1)}host: ${formatScalar(s.database?.host)}`,
    `${indent(1)}port: ${formatScalar(s.database?.port)}`,
    `${indent(1)}name: ${formatScalar(s.database?.name)}`,
    `${indent(1)}username: ${formatScalar(s.database?.username)}`,
    `${indent(1)}password: ${formatScalar(s.database?.password)}`,
    `${indent(1)}connection-pool-size: ${formatScalar(s.database?.connectionPoolSize)}`,
    '',
    'update-checker:',
    `${indent(1)}enabled: ${formatScalar(s.updateChecker?.enabled)}`,
    `${indent(1)}print-to-console: ${formatScalar(s.updateChecker?.printToConsole)}`,
    `${indent(1)}notify-in-game: ${formatScalar(s.updateChecker?.notifyInGame)}`,
    '',
    `debug: ${formatScalar(s.debug)}`,
    '',
  )
  return lines.join('\n')
}

function buildCheck(lines, name, check) {
  lines.push(`${name}:`)
  lines.push(`${indent(1)}enabled: ${formatScalar(check.enabled)}`)
  lines.push(`${indent(1)}punishable: ${formatScalar(check.punishable)}`)
  lines.push(`${indent(1)}punishment-delay-in-seconds: ${formatScalar(check.punishmentDelayInSeconds)}`)
  lines.push(`${indent(1)}max-violations: ${formatScalar(check.maxViolations)}`)
  lines.push(`${indent(1)}punishment-commands:`)
  writeStringList(lines, check.punishmentCommands, 2)

  const baseKeys = ['enabled', 'punishable', 'punishmentDelayInSeconds', 'maxViolations', 'punishmentCommands']
  Object.entries(check).forEach(([key, value]) => {
    if (baseKeys.includes(key)) return
    const yamlKey = key
      .replace(/[A-Z]/g, m => `-${m.toLowerCase()}`)
      .replace('s-d', 'sd')
    if (Array.isArray(value)) {
      lines.push(`${indent(1)}${yamlKey}:`)
      writeStringList(lines, value, 2)
    } else {
      lines.push(`${indent(1)}${yamlKey}: ${formatScalar(value)}`)
    }
  })
  lines.push('')
}

export function buildChecksYaml(s) {
  const lines = [
    '# TotemGuard checks — generated by SConfig',
    '',
    `default-punishment: ${formatScalar(s.defaultPunishment)}`,
    '',
  ]
  Object.entries(s.map || {}).forEach(([name, check]) => buildCheck(lines, name, check))
  return lines.join('\n')
}

export function buildMessagesYaml(s) {
  const lines = [
    '# TotemGuard messages — generated by SConfig',
    '',
    `format: ${formatScalar(s.format)}`,
    `prefix: ${formatScalar(s.prefix)}`,
    '',
    'alert-format:',
    `${indent(1)}alert-format: ${formatScalar(s.alertFormat?.alertFormat)}`,
    `${indent(1)}alert-format-console: ${formatScalar(s.alertFormat?.alertFormatConsole)}`,
    `${indent(1)}alert-hover-message: |`,
  ]
  String(s.alertFormat?.alertHoverMessage || '').split('\n').forEach(line => {
    lines.push(`${indent(2)}${line}`)
  })
  lines.push(
    `${indent(1)}alert-click-command: ${formatScalar(s.alertFormat?.alertClickCommand)}`,
    `${indent(1)}dev-prefix: ${formatScalar(s.alertFormat?.devPrefix)}`,
    `${indent(1)}check-details-color:`,
    `${indent(2)}main: ${formatScalar(s.alertFormat?.checkDetailsColor?.main)}`,
    `${indent(2)}secondary: ${formatScalar(s.alertFormat?.checkDetailsColor?.secondary)}`,
    '',
    `alerts-enabled: ${formatScalar(s.alertsEnabled)}`,
    `alerts-disabled: ${formatScalar(s.alertsDisabled)}`,
    `alerts-enabled-other: ${formatScalar(s.alertsEnabledOther)}`,
    `alerts-disabled-other: ${formatScalar(s.alertsDisabledOther)}`,
    `no-permission-toggle-other: ${formatScalar(s.noPermissionToggleOther)}`,
    `alert-toggle-blocked: ${formatScalar(s.alertToggleBlocked)}`,
    `alert-brand: ${formatScalar(s.alertBrand)}`,
    '',
    'command-messages:',
  )
  writeMap(lines, s.commandMessages || {}, 1)
  lines.push('')
  return lines.join('\n')
}

function writeWebhook(lines, key, v) {
  lines.push(`${key}:`)
  lines.push(`${indent(1)}enabled: ${formatScalar(v.enabled)}`)
  lines.push(`${indent(1)}url: ${formatScalar(v.url)}`)
  lines.push(`${indent(1)}name: ${formatScalar(v.name)}`)
  lines.push(`${indent(1)}color: ${formatScalar(v.color)}`)
  lines.push(`${indent(1)}title: ${formatScalar(v.title)}`)
  lines.push(`${indent(1)}profile-image: ${formatScalar(v.profileImage)}`)
  lines.push(`${indent(1)}timestamp: ${formatScalar(v.timestamp)}`)
  lines.push(`${indent(1)}footer: ${formatScalar(v.footer)}`)
  lines.push('')
}

export function buildWebhooksYaml(s) {
  const lines = ['# TotemGuard webhooks — generated by SConfig', '']
  writeWebhook(lines, 'alert', s.alert || {})
  writeWebhook(lines, 'punishment', s.punishment || {})
  return lines.join('\n')
}

export function downloadYaml(content, filename) {
  const blob = new Blob([content], { type: 'text/yaml' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}
