import { CHECK_CATALOG_UNIQUE } from './lpxData'

function indent(level) {
  return '  '.repeat(level)
}

function quoteStr(s) {
  const str = String(s ?? '')
  if (str.includes("'") && !str.includes('"')) return `"${str}"`
  if (str.includes('"')) return `'${str.replace(/'/g, "''")}'`
  return `'${str}'`
}

function formatScalar(v) {
  if (v === true) return 'true'
  if (v === false) return 'false'
  if (typeof v === 'number') return String(v)
  const s = String(v ?? '').trim()
  if (s === '') return "''"
  if (/^-?\d+(\.\d+)?$/.test(s)) return s
  return quoteStr(s)
}

function writeStringList(lines, items, level) {
  ;(items || []).forEach(item => {
    const t = String(item).trim()
    if (t) lines.push(`${indent(level)}- ${formatScalar(t)}`)
  })
}

function writeOptions(lines, options, level) {
  if (!options || typeof options !== 'object') return
  Object.entries(options).forEach(([key, val]) => {
    if (Array.isArray(val)) {
      lines.push(`${indent(level)}${key}:`)
      writeStringList(lines, val, level + 1)
    } else if (val !== null && typeof val === 'object') {
      lines.push(`${indent(level)}${key}:`)
      writeOptions(lines, val, level + 1)
    } else {
      lines.push(`${indent(level)}${key}: ${formatScalar(val)}`)
    }
  })
}

function writeCheckBlock(lines, chk, level) {
  lines.push(`${indent(level)}enabled: ${formatScalar(chk.enabled)}`)
  lines.push(`${indent(level)}punish: ${formatScalar(chk.punish)}`)
  lines.push(`${indent(level)}max-vl: ${formatScalar(chk.maxVl)}`)
  lines.push(`${indent(level)}min-vl: ${formatScalar(chk.minVl)}`)
  lines.push(`${indent(level)}punish-commands:`)
  writeStringList(lines, chk.punishCommands, level + 1)
  if (chk.buffer) {
    lines.push(`${indent(level)}buffer:`)
    lines.push(`${indent(level + 1)}max: ${formatScalar(chk.buffer.max)}`)
    lines.push(`${indent(level + 1)}multiply: ${formatScalar(chk.buffer.multiply)}`)
    lines.push(`${indent(level + 1)}decay: ${formatScalar(chk.buffer.decay)}`)
  }
  if (chk.options && Object.keys(chk.options).length > 0) {
    lines.push(`${indent(level)}options:`)
    writeOptions(lines, chk.options, level + 1)
  }
}

function buildChecksSection(s) {
  const tree = {}
  CHECK_CATALOG_UNIQUE.forEach(meta => {
    const chk = s.checks?.[meta.id]
    if (!chk) return
    if (!tree[meta.category]) tree[meta.category] = {}
    tree[meta.category][meta.type] = chk
  })

  const out = ['checks:']
  Object.entries(tree).forEach(([cat, types]) => {
    out.push(`${indent(1)}${cat}:`)
    Object.entries(types).forEach(([type, chk]) => {
      out.push(`${indent(2)}${type}:`)
      writeCheckBlock(out, chk, 3)
      out.push('')
    })
  })
  return out.join('\n').trimEnd()
}

export function buildConfigYaml(s) {
  const m = s.messages || {}
  const o = s.options || {}
  const pr = o.printer || {}
  const mech = o.mechanics || {}
  const al = o.alerts || {}
  const d = s.discord || {}
  const pl = s.packetLogger || {}

  const parts = [
    '# LPX AntiPacketExploit — generated by SConfig',
    '# https://builtbybit.com/resources/lpx-antipacketexploit.15709/',
    '',
    `license: ${formatScalar(s.license)}`,
    `force-fallback: ${formatScalar(s.forceFallback)}`,
    '',
    'messages:',
    `${indent(1)}main-color: ${formatScalar(m.mainColor)}`,
    `${indent(1)}second-color: ${formatScalar(m.secondColor)}`,
    `${indent(1)}prefix: ${formatScalar(m.prefix)}`,
    `${indent(1)}kick: ${formatScalar(m.kick)}`,
    `${indent(1)}kick-alert: ${formatScalar(m.kickAlert)}`,
    `${indent(1)}no-permission: ${formatScalar(m.noPermission)}`,
    `${indent(1)}invalid-arguments: ${formatScalar(m.invalidArguments)}`,
    `${indent(1)}injection-failure: ${formatScalar(m.injectionFailure)}`,
    `${indent(1)}update-found: ${formatScalar(m.updateFound)}`,
    `${indent(1)}null-address: ${formatScalar(m.nullAddress)}`,
    `${indent(1)}alerts:`,
    `${indent(2)}permission: ${formatScalar(m.alerts?.permission)}`,
    `${indent(2)}format: ${formatScalar(m.alerts?.format)}`,
    `${indent(2)}hover:`,
  ]
  writeStringList(parts, m.alerts?.hover, 2)
  parts.push(
    `${indent(2)}enabled: ${formatScalar(m.alerts?.enabled)}`,
    `${indent(2)}disabled: ${formatScalar(m.alerts?.disabled)}`,
    '',
    'options:',
    `${indent(1)}silent-failures: ${formatScalar(o.silentFailures)}`,
    `${indent(1)}kick-on-exception: ${formatScalar(o.kickOnException)}`,
    `${indent(1)}disable-item-decoding: ${formatScalar(o.disableItemDecoding)}`,
    `${indent(1)}hidden-command: ${formatScalar(o.hiddenCommand)}`,
    `${indent(1)}bypass-permission: ${formatScalar(o.bypassPermission)}`,
    `${indent(1)}geyser: ${formatScalar(o.geyser)}`,
    `${indent(1)}check-updates: ${formatScalar(o.checkUpdates)}`,
    `${indent(1)}bstats: ${formatScalar(o.bstats)}`,
    `${indent(1)}clear-task:`,
    `${indent(2)}enabled: ${formatScalar(o.clearTask?.enabled)}`,
    `${indent(2)}delay: ${formatScalar(o.clearTask?.delay)}`,
    `${indent(1)}printer:`,
    `${indent(2)}automatic: ${formatScalar(pr.automatic)}`,
    `${indent(2)}place-threshold: ${formatScalar(pr.placeThreshold)}`,
    `${indent(2)}disable-delay: ${formatScalar(pr.disableDelay)}`,
    `${indent(2)}alerts: ${formatScalar(pr.alerts)}`,
    `${indent(2)}permission: ${formatScalar(pr.permission)}`,
    `${indent(2)}join: ${formatScalar(pr.join)}`,
    `${indent(2)}leave: ${formatScalar(pr.leave)}`,
    `${indent(1)}mechanics:`,
    `${indent(2)}nether-portal-delay: ${formatScalar(mech.netherPortalDelay)}`,
    `${indent(2)}max-arrow-velocity: ${formatScalar(mech.maxArrowVelocity)}`,
    `${indent(2)}shears-cooldown: ${formatScalar(mech.shearsCooldown)}`,
    `${indent(2)}break-close-inventory: ${formatScalar(mech.breakCloseInventory)}`,
    `${indent(2)}trapdoor-rail-redstone: ${formatScalar(mech.trapdoorRailRedstone)}`,
    `${indent(2)}interact-container-delay: ${formatScalar(mech.interactContainerDelay)}`,
    `${indent(1)}alerts:`,
    `${indent(2)}store: ${formatScalar(al.store)}`,
    `${indent(2)}days: ${formatScalar(al.days)}`,
    `${indent(1)}server: ${formatScalar(o.server)}`,
    `${indent(1)}punish-delay: ${formatScalar(o.punishDelay)}`,
    `${indent(1)}debug: ${formatScalar(o.debug)}`,
    `${indent(1)}external-config: ${formatScalar(o.externalConfig)}`,
    '',
    'discord:',
    `${indent(1)}enabled: ${formatScalar(d.enabled)}`,
    `${indent(1)}url: ${formatScalar(d.url)}`,
    `${indent(1)}color: ${formatScalar(d.color)}`,
    `${indent(1)}content:`,
  )
  writeStringList(parts, d.content, 1)
  parts.push(
    '',
    'packet-logger:',
    `${indent(1)}heavy-packet-threshold: ${formatScalar(pl.heavyPacketThreshold)}`,
    `${indent(1)}enabled: ${formatScalar(pl.enabled)}`,
    `${indent(1)}player-mode: ${formatScalar(pl.playerMode)}`,
    `${indent(1)}players:`,
  )
  writeStringList(parts, pl.players, 1)
  parts.push(
    `${indent(1)}packet-mode: ${formatScalar(pl.packetMode)}`,
    `${indent(1)}packets:`,
  )
  writeStringList(parts, pl.packets, 1)
  parts.push('', buildChecksSection(s))
  return parts.join('\n')
}

export function downloadYaml(content, filename) {
  const blob = new Blob([content], { type: 'text/yaml' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}
