const PLACEHOLDER_RE = /%([^%\s]+)%/g

/** Multi-pass placeholder replacement (supports nested/chained values in simulation) */
export function simulatePlaceholders(text, vars, maxPasses = 6) {
  if (!text) return ''
  let result = text
  for (let pass = 0; pass < maxPasses; pass++) {
    let changed = false
    result = result.replace(PLACEHOLDER_RE, (match, key) => {
      if (Object.prototype.hasOwnProperty.call(vars, key)) {
        changed = true
        return String(vars[key])
      }
      return match
    })
    if (!changed) break
  }
  return result
}

export function findUnresolvedPlaceholders(text) {
  const matches = text.match(PLACEHOLDER_RE) || []
  return [...new Set(matches)]
}

export function buildConfigYaml(config) {
  const lines = [
    '# PlaceholderAPI — generated by SConfig',
    `check_updates: ${config.checkUpdates}`,
    `cloud_enabled: ${config.cloudEnabled}`,
    `cloud_allow_expansion_download: ${config.cloudAllowExpansionDownload}`,
    `cloud_sorting: ${config.cloudSorting || 'name'}`,
    `cloud_allow_unverified_expansions: ${config.cloudAllowUnverifiedExpansions}`,
    `debug: ${config.debug}`,
    'boolean_format:',
    `  'true': '${config.booleanTrue || 'yes'}'`,
    `  'false': '${config.booleanFalse || 'no'}'`,
  ]
  return lines.join('\n')
}

export function buildTabPluginSnippet(header, footer) {
  return [
    '# TAB plugin — header/footer snippet (config.yml)',
    'header:',
    ...header.split('\n').map(line => `  - "${escapeYamlDouble(line)}"`),
    'footer:',
    ...footer.split('\n').map(line => `  - "${escapeYamlDouble(line)}"`),
  ].join('\n')
}

export function buildScoreboardSnippet(title, linesText) {
  const lines = linesText.split('\n').filter(Boolean)
  return [
    '# Scoreboard snippet (example — adapt to your plugin)',
    `title: "${escapeYamlDouble(title)}"`,
    'lines:',
    ...lines.map(line => `  - "${escapeYamlDouble(line)}"`),
  ].join('\n')
}

export function buildEssentialsJoinSnippet(message) {
  return [
    '# EssentialsX — custom join message (config.yml)',
    'custom-join-message: |',
    ...message.split('\n').map(line => `  ${line}`),
  ].join('\n')
}

export function buildDeluxeMenusItemSnippet(name, loreLines) {
  const lore = loreLines.split('\n').filter(Boolean)
  return [
    '# DeluxeMenus — item display snippet',
    `display_name: "${escapeYamlDouble(name)}"`,
    'lore:',
    ...lore.map(line => `  - "${escapeYamlDouble(line)}"`),
  ].join('\n')
}

function escapeYamlDouble(str) {
  return String(str).replace(/\\/g, '\\\\').replace(/"/g, '\\"')
}

export function downloadText(content, filename) {
  const blob = new Blob([content], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

export const MC_COLORS = [
  { code: '0', hex: '#000000' },
  { code: '1', hex: '#0000AA' },
  { code: '2', hex: '#00AA00' },
  { code: '3', hex: '#00AAAA' },
  { code: '4', hex: '#AA0000' },
  { code: '5', hex: '#AA00AA' },
  { code: '6', hex: '#FFAA00' },
  { code: '7', hex: '#AAAAAA' },
  { code: '8', hex: '#555555' },
  { code: '9', hex: '#5555FF' },
  { code: 'a', hex: '#55FF55' },
  { code: 'b', hex: '#55FFFF' },
  { code: 'c', hex: '#FF5555' },
  { code: 'd', hex: '#FF55FF' },
  { code: 'e', hex: '#FFFF55' },
  { code: 'f', hex: '#FFFFFF' },
]

const MC_FORMATS = [
  { code: 'l', style: { fontWeight: 'bold' } },
  { code: 'o', style: { fontStyle: 'italic' } },
  { code: 'n', style: { textDecoration: 'underline' } },
  { code: 'm', style: { textDecoration: 'line-through' } },
  { code: 'k', style: { filter: 'blur(3px)' } },
  { code: 'r', style: {} },
]

/** Parse Minecraft color codes into renderable spans */
export function parseMcText(text) {
  const parts = []
  const regex = /[&§]([0-9a-fk-orA-FK-OR])/g
  let last = 0
  let currentColor = '#FFFFFF'
  let currentStyle = {}
  let match
  while ((match = regex.exec(text)) !== null) {
    if (match.index > last) {
      parts.push({ text: text.slice(last, match.index), color: currentColor, style: { ...currentStyle }, unresolved: false })
    }
    const code = match[1].toLowerCase()
    const color = MC_COLORS.find(c => c.code === code)
    const fmt = MC_FORMATS.find(f => f.code === code)
    if (color) {
      currentColor = color.hex
      currentStyle = {}
    } else if (fmt) {
      if (code === 'r') {
        currentColor = '#FFFFFF'
        currentStyle = {}
      } else {
        currentStyle = { ...currentStyle, ...fmt.style }
      }
    }
    last = match.index + match[0].length
  }
  if (last < text.length) {
    parts.push({ text: text.slice(last), color: currentColor, style: { ...currentStyle }, unresolved: false })
  }
  return parts
}

/** Split simulated text into colored spans, highlighting unresolved %tokens% */
export function parseMcTextWithUnresolved(text) {
  const segments = []
  const tokenRe = /(%[^%\s]+%)/g
  let last = 0
  let m
  while ((m = tokenRe.exec(text)) !== null) {
    if (m.index > last) {
      segments.push({ raw: text.slice(last, m.index), unresolved: false })
    }
    segments.push({ raw: m[1], unresolved: true })
    last = m.index + m[0].length
  }
  if (last < text.length) segments.push({ raw: text.slice(last), unresolved: false })

  const parts = []
  for (const seg of segments) {
    if (seg.unresolved) {
      parts.push({ text: seg.raw, color: '#f97316', style: { fontWeight: 'bold' }, unresolved: true })
    } else {
      parts.push(...parseMcText(seg.raw).map(p => ({ ...p, unresolved: false })))
    }
  }
  return parts
}
