function indent(level) {
  return '  '.repeat(level)
}

function quoteStr(s) {
  const str = String(s ?? '')
  if (str.includes("'") && !str.includes('"')) return `"${str}"`
  if (str.includes('"')) return `'${str.replace(/'/g, "''")}'`
  return `'${str}'`
}

function formatScalar(v) {
  if (v === true) return 'true'
  if (v === false) return 'false'
  if (typeof v === 'number') return String(v)
  const s = String(v ?? '').trim()
  if (s === '') return "''"
  if (/^-?\d+(\.\d+)?$/.test(s)) return s
  return quoteStr(s)
}

export function buildConfigYaml(s) {
  const lines = [
    '# GrimAC config — generated by SConfig',
    '# https://github.com/GrimAnticheat/Grim',
    '',
    'alerts:',
    `${indent(1)}print-to-console: ${formatScalar(s.alerts?.printToConsole)}`,
    `${indent(1)}proxy:`,
    `${indent(2)}send: ${formatScalar(s.alerts?.proxySend)}`,
    `${indent(2)}receive: ${formatScalar(s.alerts?.proxyReceive)}`,
    '',
    'verbose:',
    `${indent(1)}print-to-console: ${formatScalar(s.verbose?.printToConsole)}`,
    '',
    `check-for-updates: ${formatScalar(s.checkForUpdates)}`,
    '',
    'client-brand:',
    `${indent(1)}ignored-clients:`,
  ]
  ;(s.clientBrand?.ignoredClients || []).forEach(c => lines.push(`${indent(2)}- ${formatScalar(c)}`))
  lines.push(
    `${indent(1)}disconnect-blacklisted-forge-versions: ${formatScalar(s.clientBrand?.disconnectBlacklistedForge)}`,
    '',
    'spectators:',
    `${indent(1)}hide-regardless: ${formatScalar(s.spectators?.hideRegardless)}`,
    `${indent(1)}allowed-worlds:`,
  )
  const worlds = s.spectators?.allowedWorlds || []
  if (worlds.length) worlds.forEach(w => lines.push(`${indent(2)}- ${formatScalar(w)}`))
  else lines.push(`${indent(2)}- ""`)

  lines.push(
    '',
    `max-transaction-time: ${formatScalar(s.general?.maxTransactionTime)}`,
    `disable-pong-cancelling: ${formatScalar(s.general?.disablePongCancelling)}`,
    `disable-default-resync-handler: ${formatScalar(s.general?.disableDefaultResyncHandler)}`,
    `cancel-duplicate-packet: ${formatScalar(s.general?.cancelDuplicatePacket)}`,
    `ignore-duplicate-packet-rotation: ${formatScalar(s.general?.ignoreDuplicatePacketRotation)}`,
    '',
    'Simulation:',
    `${indent(1)}setback-decay-multiplier: ${formatScalar(s.simulation?.setbackDecayMultiplier)}`,
    `${indent(1)}threshold: ${formatScalar(s.simulation?.threshold)}`,
    `${indent(1)}immediate-setback-threshold: ${formatScalar(s.simulation?.immediateSetbackThreshold)}`,
    `${indent(1)}max-advantage: ${formatScalar(s.simulation?.maxAdvantage)}`,
    `${indent(1)}max-ceiling: ${formatScalar(s.simulation?.maxCeiling)}`,
    `${indent(1)}setback-violation-threshold: ${formatScalar(s.simulation?.setbackViolationThreshold)}`,
    '',
    'Phase:',
    `${indent(1)}setbackvl: ${formatScalar(s.phase?.setbackvl)}`,
    `${indent(1)}decay: ${formatScalar(s.phase?.decay)}`,
    '',
    'AirLiquidPlace:',
    `${indent(1)}cancelvl: ${formatScalar(s.place?.airLiquidCancelvl)}`,
    'FabricatedPlace:',
    `${indent(1)}cancelvl: ${formatScalar(s.place?.fabricatedCancelvl)}`,
    'FarPlace:',
    `${indent(1)}cancelvl: ${formatScalar(s.place?.farCancelvl)}`,
    'PositionPlace:',
    `${indent(1)}cancelvl: ${formatScalar(s.place?.positionCancelvl)}`,
    'RotationPlace:',
    `${indent(1)}cancelvl: ${formatScalar(s.place?.rotationCancelvl)}`,
    '',
    'NoSlow:',
    `${indent(1)}threshold: ${formatScalar(s.noSlow?.threshold)}`,
    `${indent(1)}setbackvl: ${formatScalar(s.noSlow?.setbackvl)}`,
    `${indent(1)}decay: ${formatScalar(s.noSlow?.decay)}`,
    '',
    'Knockback:',
    `${indent(1)}setback-decay-multiplier: ${formatScalar(s.knockback?.setbackDecayMultiplier)}`,
    `${indent(1)}threshold: ${formatScalar(s.knockback?.threshold)}`,
    `${indent(1)}immediate-setback-threshold: ${formatScalar(s.knockback?.immediateSetbackThreshold)}`,
    `${indent(1)}max-advantage: ${formatScalar(s.knockback?.maxAdvantage)}`,
    `${indent(1)}max-ceiling: ${formatScalar(s.knockback?.maxCeiling)}`,
    '',
    'Explosion:',
    `${indent(1)}threshold: ${formatScalar(s.explosion?.threshold)}`,
    `${indent(1)}setbackvl: ${formatScalar(s.explosion?.setbackvl)}`,
    '',
    'TimerA:',
    `${indent(1)}setbackvl: ${formatScalar(s.timer?.timerASetbackvl)}`,
    `${indent(1)}drift: ${formatScalar(s.timer?.drift)}`,
    '',
    'TimerLimit:',
    `${indent(1)}ping-abuse-limit-threshold: ${formatScalar(s.timer?.timerLimitPingThreshold)}`,
    '',
    'NegativeTimer:',
    `${indent(1)}drift: ${formatScalar(s.timer?.negativeTimerDrift)}`,
    '',
    'VehicleTimer:',
    `${indent(1)}setbackvl: ${formatScalar(s.timer?.vehicleTimerSetbackvl)}`,
    '',
    'PacketOrderI:',
    `${indent(1)}exempt-placing-while-digging: ${formatScalar(s.packetOrder?.exemptPlacingWhileDigging)}`,
    '',
    'Reach:',
    `${indent(1)}threshold: ${formatScalar(s.reach?.threshold)}`,
    `${indent(1)}block-impossible-hits: ${formatScalar(s.reach?.blockImpossibleHits)}`,
    `${indent(1)}enable-post-packet: ${formatScalar(s.reach?.enablePostPacket)}`,
    '',
    'exploit:',
    `${indent(1)}allow-sprint-jumping-when-using-elytra: ${formatScalar(s.exploit?.allowSprintJumpElytra)}`,
    `${indent(1)}allow-building-on-ghostblocks: ${formatScalar(s.exploit?.allowBuildingGhostblocks)}`,
    `${indent(1)}distance-to-check-if-ghostblocks: ${formatScalar(s.exploit?.distanceGhostblocks)}`,
    '',
    `debug-pipeline-on-join: ${formatScalar(s.flags?.debugPipelineOnJoin)}`,
    `experimental-checks: ${formatScalar(s.flags?.experimentalChecks)}`,
    `reset-item-usage-on-item-update: ${formatScalar(s.flags?.resetItemOnUpdate)}`,
    `reset-item-usage-on-attack: ${formatScalar(s.flags?.resetItemOnAttack)}`,
    `reset-item-usage-on-slot-change: ${formatScalar(s.flags?.resetItemOnSlotChange)}`,
    `reset-item-usage-on-item-use: ${formatScalar(s.flags?.resetItemOnItemUse)}`,
    `packet-spam-threshold: ${formatScalar(s.flags?.packetSpamThreshold)}`,
    `debug-packet-cancel: ${formatScalar(s.flags?.debugPacketCancel)}`,
    `max-ping-out-of-flying: ${formatScalar(s.flags?.maxPingOutOfFlying)}`,
    `max-ping-firework-boost: ${formatScalar(s.flags?.maxPingFireworkBoost)}`,
    '',
    `config-flavor: ${formatScalar(s.configFlavor)}`,
    `config-version: ${formatScalar(s.configVersion)}`,
  )

  return lines.join('\n') + '\n'
}

export function buildPunishmentsYaml(s) {
  const lines = [
    '# GrimAC punishments — generated by SConfig',
    '',
    'Punishments:',
  ]
  ;(s.punishments || []).forEach(cat => {
    if (!cat.name?.trim()) return
    lines.push(`  ${cat.name.trim()}:`)
    lines.push(`${indent(2)}remove-violations-after: ${formatScalar(cat.removeViolationsAfter)}`)
    lines.push(`${indent(2)}checks:`)
    ;(cat.checks || []).forEach(ch => {
      if (ch?.trim()) lines.push(`${indent(3)}- ${formatScalar(ch.trim())}`)
    })
    lines.push(`${indent(2)}commands:`)
    ;(cat.commands || []).forEach(cmd => {
      if (cmd?.trim()) lines.push(`${indent(3)}- ${formatScalar(cmd.trim())}`)
    })
    lines.push('')
  })
  return lines.join('\n').trimEnd() + '\n'
}

export function buildProjectYaml(s, file) {
  if (file === 'punishments') return buildPunishmentsYaml(s)
  return buildConfigYaml(s)
}

export function downloadYaml(content, filename) {
  const blob = new Blob([content], { type: 'text/yaml' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}
