function yamlQuote(str) {
  if (str == null) return '""'
  return `"${String(str).replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`
}

function yamlBool(v) {
  return v ? 'true' : 'false'
}

function indentLines(lines, spaces = 2) {
  const pad = ' '.repeat(spaces)
  return lines.map(l => `${pad}${l}`)
}

function yamlList(key, items, indent = 0) {
  const pad = ' '.repeat(indent)
  if (!items?.length) return [`${pad}${key}: []`]
  const out = [`${pad}${key}:`]
  items.forEach(item => out.push(`${pad}  - ${yamlQuote(item)}`))
  return out
}

export function buildGroupsYaml(state) {
  const lines = ['# TAB groups.yml — generated by SConfig', '']
  state.groups.forEach(g => {
    if (g.name === '_DEFAULT_') return
    lines.push(`${g.name}:`)
    if (g.tabprefix) lines.push(`  tabprefix: ${yamlQuote(g.tabprefix)}`)
    if (g.tabsuffix) lines.push(`  tabsuffix: ${yamlQuote(g.tabsuffix)}`)
    if (g.tagprefix) lines.push(`  tagprefix: ${yamlQuote(g.tagprefix)}`)
    if (g.tagsuffix) lines.push(`  tagsuffix: ${yamlQuote(g.tagsuffix)}`)
    if (g.customtabname && g.customtabname !== '%player_name%') {
      lines.push(`  customtabname: ${yamlQuote(g.customtabname)}`)
    }
    lines.push('')
  })
  const def = state.groups.find(g => g.name === '_DEFAULT_')
  if (def) {
    lines.push('_DEFAULT_:')
    if (def.tabprefix) lines.push(`  tabprefix: ${yamlQuote(def.tabprefix)}`)
    if (def.tabsuffix) lines.push(`  tabsuffix: ${yamlQuote(def.tabsuffix)}`)
    if (def.tagprefix) lines.push(`  tagprefix: ${yamlQuote(def.tagprefix)}`)
    if (def.tagsuffix) lines.push(`  tagsuffix: ${yamlQuote(def.tagsuffix)}`)
    if (def.customtabname) lines.push(`  customtabname: ${yamlQuote(def.customtabname)}`)
  }
  return lines.join('\n').trim() + '\n'
}

export function buildConfigYaml(state) {
  const lines = [
    '# TAB config.yml — generated by SConfig',
    `# Profile: ${state.profileName}`,
    '',
    'header-footer:',
    `  enabled: ${yamlBool(state.headerFooter.enabled)}`,
    '  designs:',
  ]

  state.headerFooter.designs.forEach(d => {
    lines.push(`    ${d.name}:`)
    if (d.displayCondition?.trim()) {
      lines.push(`      display-condition: ${yamlQuote(d.displayCondition)}`)
    }
    lines.push(...yamlList('header', d.header, 6))
    lines.push(...yamlList('footer', d.footer, 6))
  })

  lines.push(
    '',
    'tablist-name-formatting:',
    `  enabled: ${yamlBool(state.tablistFormatting.enabled)}`,
  )
  if (state.tablistFormatting.disableCondition) {
    lines.push(`  disable-condition: ${yamlQuote(state.tablistFormatting.disableCondition)}`)
  }

  const st = state.scoreboardTeams
  lines.push(
    '',
    'scoreboard-teams:',
    `  enabled: ${yamlBool(st.enabled)}`,
    `  enable-collision: ${yamlBool(st.enableCollision)}`,
    `  invisible-nametags: ${yamlBool(st.invisibleNametags)}`,
    '  sorting-types:',
  )
  st.sortingTypes.forEach(s => lines.push(`    - ${yamlQuote(s)}`))
  lines.push(
    `  case-sensitive-sorting: ${yamlBool(st.caseSensitiveSorting)}`,
    `  can-see-friendly-invisibles: ${yamlBool(st.canSeeFriendlyInvisibles)}`,
  )
  if (st.disableCondition) lines.push(`  disable-condition: ${yamlQuote(st.disableCondition)}`)

  const plo = state.playerlistObjective
  lines.push(
    '',
    'playerlist-objective:',
    `  enabled: ${yamlBool(plo.enabled)}`,
    `  value: ${yamlQuote(plo.value)}`,
    `  fancy-value: ${yamlQuote(plo.fancyValue)}`,
    `  title: ${yamlQuote(plo.title)}`,
    `  render-type: ${plo.renderType || 'INTEGER'}`,
  )
  if (plo.disableCondition) lines.push(`  disable-condition: ${yamlQuote(plo.disableCondition)}`)

  const bl = state.belownameObjective
  lines.push(
    '',
    'belowname-objective:',
    `  enabled: ${yamlBool(bl.enabled)}`,
    `  value: ${yamlQuote(bl.value)}`,
    `  fancy-value: ${yamlQuote(bl.fancyValue)}`,
    `  fancy-value-default: ${yamlQuote(bl.fancyValueDefault || 'NPC')}`,
    `  title: ${yamlQuote(bl.title)}`,
  )
  if (bl.disableCondition) lines.push(`  disable-condition: ${yamlQuote(bl.disableCondition)}`)

  const sb = state.scoreboard
  lines.push(
    '',
    'scoreboard:',
    `  enabled: ${yamlBool(sb.enabled)}`,
    `  toggle-command: ${yamlQuote(sb.toggleCommand)}`,
    `  remember-toggle-choice: ${yamlBool(sb.rememberToggleChoice)}`,
    `  hidden-by-default: ${yamlBool(sb.hiddenByDefault)}`,
    `  delay-on-join-milliseconds: ${sb.delayOnJoinMs ?? 0}`,
    '  scoreboards:',
  )
  sb.boards.forEach(b => {
    lines.push(`    ${b.key}:`)
    lines.push(`      title: ${yamlQuote(b.title)}`)
    if (b.displayCondition?.trim()) {
      lines.push(`      display-condition: ${yamlQuote(b.displayCondition)}`)
    }
    lines.push(...yamlList('lines', b.lines, 6))
  })

  const bb = state.bossbar
  lines.push(
    '',
    'bossbar:',
    `  enabled: ${yamlBool(bb.enabled)}`,
    `  toggle-command: ${yamlQuote(bb.toggleCommand)}`,
    `  remember-toggle-choice: ${yamlBool(bb.rememberToggleChoice)}`,
    `  hidden-by-default: ${yamlBool(bb.hiddenByDefault)}`,
    '  bars:',
  )
  bb.bars.forEach(bar => {
    lines.push(`    ${bar.key}:`)
    lines.push(`      style: ${yamlQuote(bar.style)}`)
    lines.push(`      color: ${yamlQuote(bar.color)}`)
    lines.push(`      progress: ${yamlQuote(String(bar.progress))}`)
    lines.push(`      text: ${yamlQuote(bar.text)}`)
  })

  const ph = state.placeholders
  lines.push(
    '',
    'placeholders:',
    `  date-format: ${yamlQuote(ph.dateFormat)}`,
    `  time-format: ${yamlQuote(ph.timeFormat)}`,
    `  time-offset: ${ph.timeOffset ?? 0}`,
    `  register-tab-expansion: ${yamlBool(ph.registerTabExpansion)}`,
    `  locale: ${yamlQuote(ph.locale)}`,
    '',
    'primary-group-finding-list:',
  )
  state.primaryGroupFindingList.forEach(g => lines.push(`  - ${yamlQuote(g)}`))
  lines.push(
    '',
    `debug: ${yamlBool(state.debug)}`,
    '',
    'config-version: 6',
  )

  return lines.join('\n')
}

export function buildProjectExport(state) {
  return {
    config: buildConfigYaml(state),
    groups: buildGroupsYaml(state),
  }
}

export function downloadText(content, filename) {
  const blob = new Blob([content], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}
