import { yamlQuote, yamlList } from '../shopShared'
import { buildItemLore } from './shopGuiPlusData'

function buildItemBlock(item, indent) {
  const pad = ' '.repeat(indent)
  const lines = [`${pad}type: ${item.type || 'item'}`]

  if (item.type === 'permission' && item.permission) {
    lines.push(`${pad}permission: ${yamlQuote(item.permission)}`)
  }

  lines.push(`${pad}item:`)
  lines.push(`${pad}  material: ${item.material || 'STONE'}`)
  if (item.quantity && item.quantity !== 1) lines.push(`${pad}  quantity: ${item.quantity}`)
  if (item.name) lines.push(`${pad}  name: ${yamlQuote(item.name)}`)
  const lore = buildItemLore(item)
  if (lore.length) lines.push(...yamlList('lore', lore, indent + 2))

  if (item.type === 'item') {
    if (item.buyPrice != null && item.buyPrice >= 0) lines.push(`${pad}buyPrice: ${item.buyPrice}`)
    if (item.sellPrice != null && item.sellPrice >= 0) lines.push(`${pad}sellPrice: ${item.sellPrice}`)
    if (item.sellOnly) lines.push(`${pad}sellOnly: true`)
    if (item.buyOnly) lines.push(`${pad}buyOnly: true`)
  }

  if (item.type === 'command' && item.commands?.length) {
    lines.push(...yamlList('commands', item.commands, indent))
  }

  lines.push(`${pad}slot: ${item.slot}`)
  return lines
}

export function buildShopYaml(shop) {
  const id = shop.shopId || 'shop'
  const lines = [
    `# ShopGUI+ — generated by SConfig`,
    `# File: plugins/ShopGUIPlus/shops/${id}.yml`,
    '',
    `${id}:`,
    `  name: ${yamlQuote(shop.name)}`,
    `  size: ${shop.size || 54}`,
  ]

  if (shop.fillItem?.material) {
    lines.push('  fillItem:')
    lines.push(`    material: ${shop.fillItem.material}`)
    if (shop.fillItem.name) lines.push(`    name: ${yamlQuote(shop.fillItem.name)}`)
  }

  lines.push('  items:')
  shop.items.forEach((item, idx) => {
    lines.push(`    ${idx + 1}:`)
    lines.push(...buildItemBlock(item, 6))
  })

  return lines.join('\n').trim() + '\n'
}

export function buildMenuItemsYaml(shops) {
  const lines = [
    '# Add to plugins/ShopGUIPlus/config.yml → shopMenuItems:',
    'shopMenuItems:',
  ]
  shops.forEach((shop, idx) => {
    const icon = shop.menuIcon || {}
    lines.push(`  ${idx + 1}:`)
    lines.push('    item:')
    lines.push(`      material: ${icon.material || 'CHEST'}`)
    lines.push(`      quantity: ${icon.quantity || 1}`)
    lines.push(`      name: ${yamlQuote(icon.name || shop.name)}`)
    lines.push(`    shop: ${yamlQuote(shop.shopId)}`)
    lines.push(`    slot: ${shop.menuSlot ?? idx}`)
  })
  return lines.join('\n').trim() + '\n'
}

export function buildFullExport(state) {
  const shopYamls = state.shops.map(s => buildShopYaml(s)).join('\n')
  return `${shopYamls}\n${buildMenuItemsYaml(state.shops)}`
}
